{
 "title": "vmr-chat",
 "description": "Metrics about Grafana",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "GRPC Response Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(grpc_response_time_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(vertx_http_server_responseTime_seconds_bucket[10m]))"
    }
   ]
  },
  {
   "title": "Database Query Time In Miliseconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(database_query_time_seconds_bucket[10m]))"
    }
   ]
  },
  {
   "title": "Redis Query Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(cache_query_time_seconds_bucket[10m]))"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vertx_http_server_requestCount_total[5m])"
    }
   ]
  },
  {
   "title": "JVM Thread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "live threads" },
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "daemon threads" }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[1m])/rate(jvm_gc_pause_seconds_count[1m])"
    },
    {}
   ]
  },
  {
   "title": "gRPC Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "request/s" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_response_time_seconds_count[10s])"
    }
   ]
  }
 ]
}