FROM openjdk:8

ADD ./configs /vmr-chat

ADD ./bundle.jar /vmr-chat

WORKDIR /vmr-chat

EXPOSE 8080 8081 8082

ENTRYPOINT java -jar -Dvmr-config-file=./configuration.yml -Dvmr-redis-config-file=redis.yml -Dlog4j2.configurationFile=./log4j2.xml \
    bundle.jar