const codes = {
  USERNAME_NOT_EXISTED: 'USERNAME_NOT_EXISTED',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  USERNAME_EXISTED: 'USERNAME_EXISTED',
  CREDENTIALS_NOTVALID: 'CREDENTIALS_NOTVALID'
};

export default codes;